#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 15 07:18:29 2020

@author: silasjimmy
"""

from AK47 import GameGui
        
if __name__ == "__main__":
    game = GameGui()
    game.mainloop()